name: 'container-dependency-submission-action'
description: 'Container Dependency Submission API Action'

inputs:
  repository:
    description: Repository Owner and Repository Name
    default: ${{ github.repository }}

  token:
    description: GitHub Personal Access Token
    default: ${{ github.token }}

  container:
    description: "Name of the pre-built container image"

  dockerfile:
    description: "Path to the Dockerfile you want to build"

  argvs:
    description: Additional Arguments

runs:
  using: "composite"
  steps:
    # [optional] Make sure your version of Python is installed
    # - uses: actions/setup-python@v2
    #   with:
    #     python-version: '3.10'

    - shell: bash
      run: |
        export PYTHONPATH=${{ github.action_path }}:${{ github.action_path }}/vendor
        python3 -m cdsa \
          --github-token "${{ inputs.token }}" \
          --github-repository "${{ inputs.repository }}" \
          --container "${{ inputs.container }}" \
          --dockerfile "${{ inputs.dockerfile }}" \
          ${{ inputs.argvs }}

