name: Python Action Build & Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3

    - name: "Set up Python ${{ matrix.python-version }}"
      uses: actions/setup-python@v3
      with:
        python-version: "${{ matrix.python-version }}"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv sync

    - name: Run Tests
      run: |
        PYTHONPATH=$PWD:$PWD/vendor
        if [[ -d "./tests" ]]; then
            python -m unittest discover -v -s ./tests -p "test_*.py"
        fi

    - name: Run Main
      env:
        GITHUB_TOKEN: ${{ github.token }}
        DEBUG: 1
      run: |
        PYTHONPATH=$PWD:$PWD/vendor
        pipenv run main -d "./examples/Dockerfile"

  action-test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v3
    - name: Run action
      uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
